import Vue from "vue";
import Vuex from "vuex";

Vue.use(Vuex);

export default new Vuex.Store({
  state: {
    adminUserName: "Simon Pegg",
    searchHistory: [],
    searchHistoryNew: false,
    shares: [],
    sharesNew: false,
    searchReturn: [
      {
        fullName: "Lewis P. Newman",
        badgeNumber: 22973,
        personifyNumber: 1669071585199,
        location: "Grimsby",
        expoBadge: false,
        bruteForceLock: false,
        password: "ANV56QXC9KU",
        userName: "mauris.eu@risusInmi.com",
        emailAddress: "auctor.non.feugiat@Fuscemilorem.edu",
        memberType: "",
        children: [
          {
            fullName: "Lani X. Roy",
            badgeNumber: 52207,
            personifyNumber: 1613040497999,
            location: "Luton",
            expoBadge: false,
            bruteForceLock: false,
            password: "VAE92HQE8CZ",
            userName: "ullamcorper@vulputaterisus.co.uk",
            emailAddress: "a@aliquetliberoInteger.edu",
            memberType: "AI",
            children: []
          },
          {
            fullName: "Montana O. Bauer",
            badgeNumber: 74813,
            personifyNumber: 1626091308399,
            location: "Bellingen",
            expoBadge: true,
            bruteForceLock: false,
            password: "TND68BWP2IY",
            userName: "scelerisque@facilisi.ca",
            emailAddress: "ligula.Nullam.feugiat@utmiDuis.net",
            memberType: "",
            children: []
          }
        ]
      },
      {
        fullName: "David Y. Wilder",
        badgeNumber: 75988,
        personifyNumber: 1696062374299,
        location: "Polatlı",
        expoBadge: false,
        bruteForceLock: false,
        password: "GRW95WZD9VY",
        userName: "neque.et@neque.net",
        emailAddress: "Donec@quis.org",
        memberType: "",
        children: [
          {
            fullName: "David Y. Wilder",
            badgeNumber: 75988,
            personifyNumber: 1696062374299,
            location: "Polatlı",
            expoBadge: false,
            bruteForceLock: false,
            password: "GRW95WZD9VY",
            userName: "neque.et@neque.net",
            emailAddress: "Donec@quis.org",
            memberType: "",
            children: []
          }
        ]
      },
      {
        fullName: "Chelsea F. Fox",
        badgeNumber: 99313,
        personifyNumber: 1612112543999,
        location: "Kitchener",
        expoBadge: true,
        bruteForceLock: false,
        password: "FBH88DFP5CD",
        userName: "faucibus@sagittis.com",
        emailAddress: "vel@Nulla.net",
        memberType: "FACC",
        children: []
      },
      {
        fullName: "Abel G. Tanner",
        badgeNumber: 75798,
        personifyNumber: 1657052920399,
        location: "Clearwater Municipal District",
        expoBadge: true,
        bruteForceLock: false,
        password: "CST13MZW5RM",
        userName: "nibh.Quisque@elitCurabitursed.net",
        emailAddress: "feugiat@pharetrased.org",
        memberType: "ACC",
        children: [
          {
            fullName: "Geoffrey B. Mercer",
            badgeNumber: 28032,
            personifyNumber: 1638060815199,
            location: "Sant'Eufemia a Maiella",
            expoBadge: true,
            bruteForceLock: false,
            password: "OUZ57TAY0SY",
            userName: "risus.Donec.egestas@CuraePhasellus.edu",
            emailAddress: "dictum@fermentummetusAenean.edu",
            memberType: "",
            children: []
          },
          {
            fullName: "Astra U. Blackburn",
            badgeNumber: 5010,
            personifyNumber: 1632120900199,
            location: "Warszawa",
            expoBadge: false,
            bruteForceLock: false,
            password: "IAW39XSV5FI",
            userName: "nunc.sed@nullamagnamalesuada.co.uk",
            emailAddress: "montes.nascetur@musAenean.org",
            memberType: "",
            children: []
          }
        ]
      },
      {
        fullName: "Belle K. Freeman",
        badgeNumber: 54813,
        personifyNumber: 1653092183499,
        location: "Milano",
        expoBadge: false,
        bruteForceLock: false,
        password: "MWW93YZB8AX",
        userName: "Suspendisse.sagittis@est.ca",
        emailAddress: "sit.amet.diam@atrisus.co.uk",
        memberType: "AA",
        children: [
          {
            fullName: "Owen Z. England",
            badgeNumber: 78806,
            personifyNumber: 1608061530699,
            location: "Polpenazze del Garda",
            expoBadge: true,
            bruteForceLock: false,
            password: "NCK50SEE5QL",
            userName: "ornare@cursus.net",
            emailAddress: "Donec.consectetuer@dapibusrutrum.org",
            memberType: "NPI",
            children: []
          }
        ]
      },
      {
        fullName: "Marvin X. Stanton",
        badgeNumber: 40747,
        personifyNumber: 1657101092399,
        location: "Hulst",
        expoBadge: true,
        bruteForceLock: false,
        password: "PRT67TAP2ZX",
        userName: "neque@interdumenim.com",
        emailAddress: "Nulla.eget.metus@disparturientmontes.co.uk",
        memberType: "",
        children: []
      },
      {
        fullName: "Melodie A. Joyce",
        badgeNumber: 77146,
        personifyNumber: 1663060381499,
        location: "Whitehaven",
        expoBadge: false,
        bruteForceLock: false,
        password: "YVD48HXZ2ZL",
        userName: "malesuada.fames.ac@urna.edu",
        emailAddress: "a.felis@Cras.org",
        memberType: "FIT",
        children: []
      },
      {
        fullName: "Owen Z. England",
        badgeNumber: 78806,
        personifyNumber: 1608061530699,
        location: "Polpenazze del Garda",
        expoBadge: true,
        bruteForceLock: false,
        password: "NCK50SEE5QL",
        userName: "ornare@cursus.net",
        emailAddress: "Donec.consectetuer@dapibusrutrum.org",
        memberType: "NPI",
        children: []
      },
      {
        fullName: "Lavinia W. Mcgee",
        badgeNumber: 7606,
        personifyNumber: 1686102620999,
        location: "Heist-aan-Zee",
        expoBadge: false,
        bruteForceLock: false,
        password: "STW06WRV9XE",
        userName: "dui.quis@ametconsectetuer.co.uk",
        emailAddress: "eget.massa.Suspendisse@blanditcongue.org",
        memberType: "AA",
        children: []
      },
      {
        fullName: "Bree H. Osborne",
        badgeNumber: 30222,
        personifyNumber: 1680042495199,
        location: "Morwell",
        expoBadge: false,
        bruteForceLock: false,
        password: "SYO92LVG2XK",
        userName: "Proin.vel.nisl@ipsum.org",
        emailAddress: "posuere@Namligulaelit.co.uk",
        memberType: "NPI",
        children: []
      },
      {
        fullName: "Gail C. Mcdowell",
        badgeNumber: 52482,
        personifyNumber: 1677053011499,
        location: "Paço do Lumiar",
        expoBadge: false,
        bruteForceLock: false,
        password: "NOH60UOM9WE",
        userName: "nulla.vulputate.dui@eu.org",
        emailAddress: "quis.tristique.ac@atiaculisquis.co.uk",
        memberType: "AA",
        children: [
          {
            fullName: "Colleen C. Estrada",
            badgeNumber: 22508,
            personifyNumber: 1697090251399,
            location: "Oberursel",
            expoBadge: false,
            bruteForceLock: false,
            password: "TBU67WZB5IN",
            userName: "vel@liberoat.co.uk",
            emailAddress: "Phasellus.in.felis@sagittislobortis.co.uk",
            memberType: "",
            children: []
          }
        ]
      },
      {
        fullName: "Flynn V. Mack",
        badgeNumber: 48887,
        personifyNumber: 1669062384899,
        location: "Wanneroo",
        expoBadge: false,
        bruteForceLock: false,
        password: "GJE13GMQ0UJ",
        userName: "Nulla.interdum@laoreet.com",
        emailAddress: "non.justo@sedhendrerit.edu",
        memberType: "FIT",
        children: []
      },
      {
        fullName: "Driscoll Y. Doyle",
        badgeNumber: 88890,
        personifyNumber: 1664090946499,
        location: "Westrem",
        expoBadge: true,
        bruteForceLock: false,
        password: "XXB34MYN3GF",
        userName: "neque.In.ornare@convallisin.net",
        emailAddress: "imperdiet.non@necimperdietnec.co.uk",
        memberType: "FACC",
        children: []
      },
      {
        fullName: "Ina Q. Stout",
        badgeNumber: 70036,
        personifyNumber: 1672040292799,
        location: "Cobquecura",
        expoBadge: true,
        bruteForceLock: false,
        password: "DUJ75XZI8KE",
        userName: "mauris@Quisqueporttitor.org",
        emailAddress: "non@faucibus.org",
        memberType: "AI",
        children: []
      },
      {
        fullName: "Violet H. Gilmore",
        badgeNumber: 84664,
        personifyNumber: 1642110641299,
        location: "Guildford",
        expoBadge: true,
        bruteForceLock: false,
        password: "JAP60IHZ4VI",
        userName: "ac.turpis.egestas@milorem.org",
        emailAddress: "iaculis.enim@Nunc.net",
        memberType: "",
        children: []
      },
      {
        fullName: "Lane S. Juarez",
        badgeNumber: 56384,
        personifyNumber: 1661041929199,
        location: "Slough",
        expoBadge: false,
        bruteForceLock: false,
        password: "YFE03WPJ0WO",
        userName: "dignissim@etnetuset.net",
        emailAddress: "Ut.semper@Classaptent.org",
        memberType: "AA",
        children: []
      },
      {
        fullName: "Signe L. Cherry",
        badgeNumber: 86046,
        personifyNumber: 1608080370499,
        location: "Athens",
        expoBadge: true,
        bruteForceLock: false,
        password: "IBH06FAE9EU",
        userName: "sed.tortor.Integer@consequatnec.net",
        emailAddress: "Sed.dictum.Proin@lectus.co.uk",
        memberType: "",
        children: []
      },
      {
        fullName: "Emma T. Meyer",
        badgeNumber: 71677,
        personifyNumber: 1677012116499,
        location: "ThimŽon",
        expoBadge: false,
        bruteForceLock: false,
        password: "WVO28YBQ5PX",
        userName: "ipsum.nunc@Sedcongueelit.edu",
        emailAddress: "viverra.Donec@Maecenasornareegestas.co.uk",
        memberType: "FACC",
        children: []
      },
      {
        fullName: "Zahir A. Kaufman",
        badgeNumber: 65480,
        personifyNumber: 1643121858199,
        location: "Goes",
        expoBadge: false,
        bruteForceLock: false,
        password: "HOC46QFG1XC",
        userName: "Pellentesque.ut@maurisa.com",
        emailAddress: "fringilla.est@nisiCum.org",
        memberType: "FIT",
        children: []
      },
      {
        fullName: "Conan P. Powell",
        badgeNumber: 66042,
        personifyNumber: 1626081947399,
        location: "Hamilton",
        expoBadge: false,
        bruteForceLock: false,
        password: "ESY10AVL6TI",
        userName: "vitae@mattis.net",
        emailAddress: "eget.venenatis.a@sagittisfelisDonec.co.uk",
        memberType: "",
        children: []
      },
      {
        fullName: "Kermit X. Erickson",
        badgeNumber: 32477,
        personifyNumber: 1685060134399,
        location: "Swansea",
        expoBadge: true,
        bruteForceLock: false,
        password: "KUC42OLN9VC",
        userName: "ac.eleifend.vitae@ligula.net",
        emailAddress: "id@dignissim.ca",
        memberType: "",
        children: []
      },
      {
        fullName: "Harper Q. Garner",
        badgeNumber: 23074,
        personifyNumber: 1640020719699,
        location: "Cumberland County",
        expoBadge: false,
        bruteForceLock: false,
        password: "KIO60QXX3ND",
        userName: "est.Mauris.eu@arcuiaculisenim.edu",
        emailAddress: "purus@mollisDuis.ca",
        memberType: "",
        children: []
      },
      {
        fullName: "Price S. Miranda",
        badgeNumber: 37154,
        personifyNumber: 1665040651499,
        location: "Valdivia",
        expoBadge: true,
        bruteForceLock: false,
        password: "NRK00YNT1IY",
        userName: "lorem.luctus@loremeumetus.co.uk",
        emailAddress: "malesuada@sodalesat.net",
        memberType: "FACC",
        children: []
      },
      {
        fullName: "Elijah T. Torres",
        badgeNumber: 54095,
        personifyNumber: 1617010513999,
        location: "Purranque",
        expoBadge: true,
        bruteForceLock: false,
        password: "OVA18FZK8NR",
        userName: "parturient@dignissim.net",
        emailAddress: "In.at@rutrumeu.edu",
        memberType: "AI",
        children: []
      },
      {
        fullName: "Addison G. Bradshaw",
        badgeNumber: 19421,
        personifyNumber: 1607122143299,
        location: "Maule",
        expoBadge: true,
        bruteForceLock: false,
        password: "CRQ96QDS5TM",
        userName: "bibendum.fermentum@ametrisusDonec.org",
        emailAddress: "commodo@MorbimetusVivamus.org",
        memberType: "AA",
        children: []
      },
      {
        fullName: "Kamal W. Stephenson",
        badgeNumber: 38399,
        personifyNumber: 1636010664599,
        location: "Bernburg",
        expoBadge: true,
        bruteForceLock: false,
        password: "VIO61WJJ0HI",
        userName: "diam.Proin@diamDuismi.co.uk",
        emailAddress: "elit.a.feugiat@sociis.org",
        memberType: "ACC",
        children: []
      },
      {
        fullName: "Althea B. Leonard",
        badgeNumber: 76418,
        personifyNumber: 1601081057199,
        location: "Monstreux",
        expoBadge: true,
        bruteForceLock: false,
        password: "GNY17TKA5FE",
        userName: "vitae@elit.ca",
        emailAddress: "mus.Proin@Aenean.ca",
        memberType: "AI",
        children: []
      },
      {
        fullName: "Keelie M. Roy",
        badgeNumber: 71867,
        personifyNumber: 1651051251699,
        location: "Blumenau",
        expoBadge: true,
        bruteForceLock: false,
        password: "BJB20OUK3MV",
        userName: "quam@dolorsit.edu",
        emailAddress: "scelerisque@Aliquamtinciduntnunc.org",
        memberType: "",
        children: []
      },
      {
        fullName: "Cameron A. Durham",
        badgeNumber: 57115,
        personifyNumber: 1616080852099,
        location: "Coquitlam",
        expoBadge: true,
        bruteForceLock: false,
        password: "WCQ11BCK6EL",
        userName: "Quisque.purus.sapien@Cras.com",
        emailAddress: "tincidunt@lectusconvallis.org",
        memberType: "",
        children: []
      },
      {
        fullName: "Carson R. Koch",
        badgeNumber: 23678,
        personifyNumber: 1658062737899,
        location: "Boston",
        expoBadge: true,
        bruteForceLock: false,
        password: "PXO35NHB7IO",
        userName: "tempor.lorem@metusfacilisislorem.org",
        emailAddress: "urna.Vivamus.molestie@enimdiam.ca",
        memberType: "AA",
        children: []
      },
      {
        fullName: "Naomi R. Wiggins",
        badgeNumber: 38388,
        personifyNumber: 1677111440799,
        location: "Notre-Dame-du-Nord",
        expoBadge: false,
        bruteForceLock: false,
        password: "AWZ04MMP5XM",
        userName: "arcu@Sedmolestie.org",
        emailAddress: "vitae.erat@ipsumCurabiturconsequat.org",
        memberType: "",
        children: []
      },
      {
        fullName: "Alexandra C. Higgins",
        badgeNumber: 45586,
        personifyNumber: 1642102052499,
        location: "Oldenzaal",
        expoBadge: false,
        bruteForceLock: false,
        password: "DLJ92GON9VS",
        userName: "Sed@euismodetcommodo.ca",
        emailAddress: "metus.sit@aliquamiaculis.edu",
        memberType: "FACC",
        children: []
      },
      {
        fullName: "Sandra E. Stout",
        badgeNumber: 37170,
        personifyNumber: 1605112422299,
        location: "Balclutha",
        expoBadge: true,
        bruteForceLock: false,
        password: "CAL07TSS5KI",
        userName: "Curabitur.dictum.Phasellus@elementumategestas.co.uk",
        emailAddress: "a.purus.Duis@Pellentesquetincidunt.net",
        memberType: "",
        children: []
      },
      {
        fullName: "Miranda H. Day",
        badgeNumber: 29439,
        personifyNumber: 1647121072799,
        location: "Pettoranello del Molise",
        expoBadge: false,
        bruteForceLock: false,
        password: "WYZ37KFQ3FT",
        userName: "mattis@convallisincursus.net",
        emailAddress: "elementum.lorem@vehicularisusNulla.ca",
        memberType: "ACC",
        children: []
      },
      {
        fullName: "Dexter A. Mccoy",
        badgeNumber: 98640,
        personifyNumber: 1683041119299,
        location: "Pointe-Claire",
        expoBadge: false,
        bruteForceLock: false,
        password: "FLN14TWP4IT",
        userName: "gravida.sagittis.Duis@bibendumfermentum.org",
        emailAddress: "quam@noncursus.org",
        memberType: "NPI",
        children: []
      },
      {
        fullName: "Zeph J. Hurley",
        badgeNumber: 77150,
        personifyNumber: 1631121750799,
        location: "Oelegem",
        expoBadge: false,
        bruteForceLock: false,
        password: "GKY75MND5LM",
        userName: "parturient.montes.nascetur@elitpede.org",
        emailAddress: "lobortis.nisi.nibh@Nuncullamcorpervelit.co.uk",
        memberType: "FIT",
        children: []
      },
      {
        fullName: "Daphne F. Summers",
        badgeNumber: 63783,
        personifyNumber: 1652091533499,
        location: "Albury",
        expoBadge: false,
        bruteForceLock: false,
        password: "BAN27DRE4TM",
        userName: "orci.adipiscing.non@nonjusto.net",
        emailAddress: "bibendum.sed.est@Aliquamnec.org",
        memberType: "FIT",
        children: []
      },
      {
        fullName: "Nigel X. Sellers",
        badgeNumber: 18628,
        personifyNumber: 1683010664899,
        location: "Monceau-sur-Sambre",
        expoBadge: true,
        bruteForceLock: false,
        password: "WEN71CKB9XK",
        userName: "euismod@vitae.com",
        emailAddress: "eu@ornarelectusjusto.com",
        memberType: "FACC",
        children: []
      },
      {
        fullName: "Merritt N. Craft",
        badgeNumber: 70615,
        personifyNumber: 1667082488899,
        location: "Wiener Neustadt",
        expoBadge: false,
        bruteForceLock: false,
        password: "KSD84IDB8TS",
        userName: "Curabitur.egestas.nunc@vestibulumneceuismod.edu",
        emailAddress: "malesuada.malesuada.Integer@Mauris.com",
        memberType: "",
        children: []
      },
      {
        fullName: "Demetria K. Osborn",
        badgeNumber: 77459,
        personifyNumber: 1624022090899,
        location: "Ripalta Guerina",
        expoBadge: true,
        bruteForceLock: false,
        password: "JBP57OEW3FS",
        userName: "lectus.pede.et@Curabitursed.edu",
        emailAddress: "habitant.morbi@nislMaecenasmalesuada.ca",
        memberType: "ACC",
        children: []
      },
      {
        fullName: "Josiah Q. Sharp",
        badgeNumber: 13543,
        personifyNumber: 1666082738199,
        location: "Río Bueno",
        expoBadge: false,
        bruteForceLock: false,
        password: "ELQ58KRH9GK",
        userName: "enim.mi@euismodetcommodo.org",
        emailAddress: "dolor.Fusce.feugiat@semmolestiesodales.co.uk",
        memberType: "ACC",
        children: []
      },
      {
        fullName: "Beck D. Solis",
        badgeNumber: 57320,
        personifyNumber: 1652071714599,
        location: "East Kilbride",
        expoBadge: true,
        bruteForceLock: false,
        password: "KXG64IFJ0FO",
        userName: "imperdiet.erat@nonummyutmolestie.edu",
        emailAddress: "convallis@mattisornare.edu",
        memberType: "",
        children: []
      },
      {
        fullName: "Brennan Y. Herman",
        badgeNumber: 10775,
        personifyNumber: 1618070851499,
        location: "Reana del Rojale",
        expoBadge: false,
        bruteForceLock: false,
        password: "GQD25WTL7YX",
        userName: "nisi@Quisquetinciduntpede.ca",
        emailAddress: "blandit.enim.consequat@commodoipsumSuspendisse.edu",
        memberType: "",
        children: []
      },
      {
        fullName: "Dominique H. Nieves",
        badgeNumber: 49267,
        personifyNumber: 1693071223399,
        location: "Genova",
        expoBadge: false,
        bruteForceLock: false,
        password: "GFO22HRB3DA",
        userName: "nonummy.Fusce.fermentum@rutrummagna.net",
        emailAddress: "gravida@In.com",
        memberType: "AA",
        children: []
      },
      {
        fullName: "Yoshio R. Haynes",
        badgeNumber: 73471,
        personifyNumber: 1695050979999,
        location: "Greater Sudbury",
        expoBadge: false,
        bruteForceLock: false,
        password: "GKC83SFB1HC",
        userName: "sem.ut.cursus@leoelementumsem.co.uk",
        emailAddress: "ut.mi@arcuNuncmauris.ca",
        memberType: "",
        children: []
      },
      {
        fullName: "Russell E. Bradley",
        badgeNumber: 3086,
        personifyNumber: 1699080277599,
        location: "Albisola Superiore",
        expoBadge: true,
        bruteForceLock: false,
        password: "KSF65JGG4BO",
        userName: "sit.amet.faucibus@sodalesatvelit.org",
        emailAddress: "adipiscing.non@nasceturridiculusmus.org",
        memberType: "",
        children: []
      },
      {
        fullName: "Henry K. Turner",
        badgeNumber: 98888,
        personifyNumber: 1688120978399,
        location: "Guildford",
        expoBadge: true,
        bruteForceLock: false,
        password: "ALJ33XKR5GS",
        userName: "dictum.ultricies.ligula@Nullamscelerisqueneque.edu",
        emailAddress: "sed.dictum.eleifend@nequeetnunc.edu",
        memberType: "",
        children: []
      },
      {
        fullName: "Kiara Z. Wilson",
        badgeNumber: 51969,
        personifyNumber: 1670082921099,
        location: "Rockford",
        expoBadge: true,
        bruteForceLock: false,
        password: "WLP60MWD5KR",
        userName: "Phasellus.in.felis@Pellentesque.com",
        emailAddress: "pede@cursusvestibulum.org",
        memberType: "",
        children: []
      },
      {
        fullName: "Chelsea Q. Curtis",
        badgeNumber: 60661,
        personifyNumber: 1683122545199,
        location: "Raichur",
        expoBadge: false,
        bruteForceLock: false,
        password: "MOW10VLF8BS",
        userName: "ultricies.adipiscing.enim@Namligulaelit.ca",
        emailAddress: "Donec.tempor@egestasDuis.ca",
        memberType: "FACC",
        children: []
      },
      {
        fullName: "Lareina Q. Savage",
        badgeNumber: 6330,
        personifyNumber: 1623011315499,
        location: "Welland",
        expoBadge: true,
        bruteForceLock: false,
        password: "HBI65XMY8YA",
        userName: "vulputate@maurisblandit.net",
        emailAddress: "iaculis.nec@incursus.co.uk",
        memberType: "",
        children: []
      },
      {
        fullName: "Sebastian H. Doyle",
        badgeNumber: 20876,
        personifyNumber: 1610042161399,
        location: "Völklingen",
        expoBadge: true,
        bruteForceLock: false,
        password: "STV27GLS2KC",
        userName: "eleifend.nec@utnisia.org",
        emailAddress: "egestas.urna@SuspendissesagittisNullam.com",
        memberType: "ACC",
        children: []
      },
      {
        fullName: "Wendy I. Alford",
        badgeNumber: 27963,
        personifyNumber: 1608012045699,
        location: "Stafford",
        expoBadge: false,
        bruteForceLock: false,
        password: "IGU80KTS0OY",
        userName: "Ut.tincidunt.orci@inconsequatenim.edu",
        emailAddress: "justo.nec@metus.ca",
        memberType: "AI",
        children: []
      },
      {
        fullName: "Kelsie I. Leon",
        badgeNumber: 37659,
        personifyNumber: 1652050566799,
        location: "Bolano",
        expoBadge: false,
        bruteForceLock: false,
        password: "DMO91YQJ5XS",
        userName: "nunc.sed@nec.co.uk",
        emailAddress: "Nulla@sagittis.com",
        memberType: "ACC",
        children: []
      },
      {
        fullName: "Hilary L. Marquez",
        badgeNumber: 29780,
        personifyNumber: 1615100847699,
        location: "Albany",
        expoBadge: false,
        bruteForceLock: false,
        password: "SMK56KHQ9TV",
        userName: "Proin.vel.nisl@mienim.co.uk",
        emailAddress: "elit@liberoProin.ca",
        memberType: "FACC",
        children: []
      },
      {
        fullName: "Alexa F. Johns",
        badgeNumber: 14082,
        personifyNumber: 1668072694399,
        location: "Froidchapelle",
        expoBadge: true,
        bruteForceLock: false,
        password: "FQN20TTG7MI",
        userName: "metus.Aliquam.erat@nonsapienmolestie.net",
        emailAddress: "elit.a.feugiat@Maurisvestibulumneque.org",
        memberType: "ACC",
        children: []
      },
      {
        fullName: "Chaney I. Goodwin",
        badgeNumber: 22266,
        personifyNumber: 1616061539999,
        location: "Redwater",
        expoBadge: false,
        bruteForceLock: false,
        password: "SAJ40KGB1YY",
        userName: "purus.ac.tellus@eget.ca",
        emailAddress: "a.scelerisque@NullainterdumCurabitur.edu",
        memberType: "NPI",
        children: []
      },
      {
        fullName: "Glenna F. Thornton",
        badgeNumber: 21799,
        personifyNumber: 1654110160799,
        location: "Gembloux",
        expoBadge: false,
        bruteForceLock: false,
        password: "KPA99FYU6XK",
        userName: "sed@sem.edu",
        emailAddress: "mollis@sagittissemper.net",
        memberType: "",
        children: []
      },
      {
        fullName: "Kasper A. Maxwell",
        badgeNumber: 52361,
        personifyNumber: 1670072523999,
        location: "Rishra",
        expoBadge: false,
        bruteForceLock: false,
        password: "GZO42CIG6HL",
        userName: "nunc.sed@Vivamusmolestiedapibus.edu",
        emailAddress: "Donec.porttitor.tellus@feugiattellus.org",
        memberType: "",
        children: []
      },
      {
        fullName: "Clayton O. Carver",
        badgeNumber: 23566,
        personifyNumber: 1645100160299,
        location: "Kingston",
        expoBadge: false,
        bruteForceLock: false,
        password: "MCG96GYG7LC",
        userName: "cursus.purus.Nullam@ac.com",
        emailAddress: "mattis.Integer.eu@Vivamus.ca",
        memberType: "AI",
        children: []
      },
      {
        fullName: "Casey T. Guthrie",
        badgeNumber: 47967,
        personifyNumber: 1632032825899,
        location: "Ramskapelle",
        expoBadge: false,
        bruteForceLock: false,
        password: "UAA30HUV6SW",
        userName: "ac.mattis@ornareInfaucibus.org",
        emailAddress: "feugiat.Lorem@ligulatortordictum.co.uk",
        memberType: "",
        children: []
      },
      {
        fullName: "Chelsea E. Vincent",
        badgeNumber: 50072,
        personifyNumber: 1642032455499,
        location: "Provost",
        expoBadge: false,
        bruteForceLock: false,
        password: "COD30UTE6QI",
        userName: "libero.Morbi.accumsan@risusQuisque.org",
        emailAddress: "sapien@dictum.co.uk",
        memberType: "AI",
        children: []
      },
      {
        fullName: "Lani V. Summers",
        badgeNumber: 88150,
        personifyNumber: 1695070248999,
        location: "Pitrufquén",
        expoBadge: true,
        bruteForceLock: false,
        password: "EPH74THV5UZ",
        userName: "ultrices.Vivamus@aliquamiaculis.net",
        emailAddress: "purus@Quisque.co.uk",
        memberType: "FIT",
        children: []
      },
      {
        fullName: "Joan C. Sharpe",
        badgeNumber: 52753,
        personifyNumber: 1649082931699,
        location: "Burlington",
        expoBadge: true,
        bruteForceLock: false,
        password: "IWO35KYE9BM",
        userName: "est.ac@eteuismodet.net",
        emailAddress: "augue@Incondimentum.org",
        memberType: "AI",
        children: []
      },
      {
        fullName: "Jamal J. Fowler",
        badgeNumber: 24499,
        personifyNumber: 1622110152199,
        location: "Strathcona County",
        expoBadge: true,
        bruteForceLock: false,
        password: "URB11ZCU5LM",
        userName: "urna.et@Curabitur.edu",
        emailAddress: "mauris.aliquam@tinciduntnequevitae.co.uk",
        memberType: "",
        children: []
      },
      {
        fullName: "Casey N. Kelley",
        badgeNumber: 61032,
        personifyNumber: 1601012068199,
        location: "Renfrew",
        expoBadge: true,
        bruteForceLock: false,
        password: "UAP21IZM2HL",
        userName: "aliquam.arcu.Aliquam@laoreet.net",
        emailAddress: "ante@duinec.edu",
        memberType: "",
        children: []
      },
      {
        fullName: "Amethyst B. Rollins",
        badgeNumber: 97237,
        personifyNumber: 1688021398099,
        location: "Białystok",
        expoBadge: true,
        bruteForceLock: false,
        password: "GNZ98CXE4BQ",
        userName: "Aenean.eget.magna@Aliquamultricesiaculis.com",
        emailAddress: "odio.semper@convallisantelectus.co.uk",
        memberType: "",
        children: []
      },
      {
        fullName: "Faith S. Long",
        badgeNumber: 21623,
        personifyNumber: 1615070376699,
        location: "Bilaspur",
        expoBadge: false,
        bruteForceLock: false,
        password: "XML24GBW5NF",
        userName: "arcu.Sed@aliquam.co.uk",
        emailAddress: "in.sodales@pede.edu",
        memberType: "FIT",
        children: []
      },
      {
        fullName: "Valentine C. Beasley",
        badgeNumber: 45330,
        personifyNumber: 1626070996299,
        location: "Nelson",
        expoBadge: false,
        bruteForceLock: false,
        password: "DYZ06TKD3UW",
        userName: "imperdiet.ornare.In@lobortismaurisSuspendisse.com",
        emailAddress: "ultrices.posuere.cubilia@euerosNam.ca",
        memberType: "FIT",
        children: []
      },
      {
        fullName: "Iona G. Maxwell",
        badgeNumber: 78933,
        personifyNumber: 1671021556899,
        location: "Gavirate",
        expoBadge: true,
        bruteForceLock: false,
        password: "YKA11NKN4NI",
        userName: "sollicitudin.a@eunibh.net",
        emailAddress: "luctus.ipsum.leo@risusDonecegestas.ca",
        memberType: "",
        children: []
      },
      {
        fullName: "Yen P. Savage",
        badgeNumber: 58968,
        personifyNumber: 1652010708499,
        location: "New Glasgow",
        expoBadge: false,
        bruteForceLock: false,
        password: "XIU39OJA5KL",
        userName: "Pellentesque@lobortis.com",
        emailAddress: "in.consectetuer@In.co.uk",
        memberType: "ACC",
        children: []
      },
      {
        fullName: "Cadman F. Brady",
        badgeNumber: 12998,
        personifyNumber: 1604061958199,
        location: "Fortune",
        expoBadge: true,
        bruteForceLock: false,
        password: "VLS42FYF7ND",
        userName: "adipiscing.non@Aliquam.ca",
        emailAddress: "Sed.congue@Etiamligula.net",
        memberType: "AA",
        children: []
      },
      {
        fullName: "Yael U. Weaver",
        badgeNumber: 47765,
        personifyNumber: 1649030388199,
        location: "Sterrebeek",
        expoBadge: true,
        bruteForceLock: false,
        password: "BGM81XTZ6SW",
        userName: "interdum.Sed.auctor@turpisNulla.ca",
        emailAddress: "vitae.orci@fringillacursuspurus.edu",
        memberType: "ACC",
        children: []
      },
      {
        fullName: "Vielka X. Galloway",
        badgeNumber: 41146,
        personifyNumber: 1606022927399,
        location: "Scarborough",
        expoBadge: true,
        bruteForceLock: false,
        password: "RUR62PTT8CY",
        userName: "magna@sollicitudinorci.net",
        emailAddress: "Nunc.mauris@facilisiseget.com",
        memberType: "",
        children: []
      },
      {
        fullName: "Caldwell I. Tyson",
        badgeNumber: 75540,
        personifyNumber: 1660112584699,
        location: "Kapfenberg",
        expoBadge: true,
        bruteForceLock: false,
        password: "QEZ90LZR2KE",
        userName: "dui.Fusce.diam@dolordapibus.ca",
        emailAddress: "Cum@sapien.net",
        memberType: "",
        children: []
      },
      {
        fullName: "Basil J. Clarke",
        badgeNumber: 89338,
        personifyNumber: 1690052984299,
        location: "Beerse",
        expoBadge: true,
        bruteForceLock: false,
        password: "SOS09UDL5SX",
        userName: "Nulla.eget.metus@morbitristique.net",
        emailAddress: "sagittis.placerat.Cras@nasceturridiculusmus.ca",
        memberType: "AA",
        children: []
      },
      {
        fullName: "Sean I. Golden",
        badgeNumber: 56752,
        personifyNumber: 1671010524399,
        location: "San Pietro Mussolino",
        expoBadge: false,
        bruteForceLock: false,
        password: "CIB76BGG7XU",
        userName: "risus.odio.auctor@Quisquenonummyipsum.co.uk",
        emailAddress: "erat.eget@rutrumjustraesent.edu",
        memberType: "",
        children: []
      },
      {
        fullName: "Dane I. Grimes",
        badgeNumber: 35807,
        personifyNumber: 1650022840999,
        location: "Bad Vilbel",
        expoBadge: false,
        bruteForceLock: false,
        password: "USJ31APS3NK",
        userName: "et.arcu@eratsemperrutrum.co.uk",
        emailAddress: "non.lorem.vitae@consectetueradipiscingelit.com",
        memberType: "FIT",
        children: []
      },
      {
        fullName: "Hamilton W. Ramsey",
        badgeNumber: 52800,
        personifyNumber: 1650071119499,
        location: "Westkerke",
        expoBadge: true,
        bruteForceLock: false,
        password: "NGU76NFR2HN",
        userName: "ut.aliquam@nec.net",
        emailAddress: "Vestibulum.ut@Maurisutquam.edu",
        memberType: "",
        children: []
      },
      {
        fullName: "Price T. Snyder",
        badgeNumber: 69793,
        personifyNumber: 1691011833699,
        location: "Vezin",
        expoBadge: true,
        bruteForceLock: false,
        password: "RKB99MGK5TR",
        userName: "lacus.Mauris@diamSed.edu",
        emailAddress: "parturient.montes@Aeneansedpede.org",
        memberType: "",
        children: []
      },
      {
        fullName: "Wang I. Barr",
        badgeNumber: 26807,
        personifyNumber: 1623040474399,
        location: "Otranto",
        expoBadge: false,
        bruteForceLock: false,
        password: "RRE53VJF3XT",
        userName: "odio.semper.cursus@ligulaNullam.edu",
        emailAddress: "risus.quis.diam@accumsanconvallis.net",
        memberType: "FACC",
        children: []
      },
      {
        fullName: "Kitra X. Gomez",
        badgeNumber: 95871,
        personifyNumber: 1638122795899,
        location: "Bonnyrigg",
        expoBadge: false,
        bruteForceLock: false,
        password: "QYL69TYV9UT",
        userName: "Sed.id.risus@nislelementum.org",
        emailAddress: "in.magna@posuerecubiliaCurae.co.uk",
        memberType: "",
        children: []
      },
      {
        fullName: "Ann H. Roy",
        badgeNumber: 79651,
        personifyNumber: 1673091815899,
        location: "Winnipeg",
        expoBadge: true,
        bruteForceLock: false,
        password: "CJZ62JTH5IF",
        userName: "nec.mollis@ante.net",
        emailAddress: "urna@dignissimpharetraNam.ca",
        memberType: "",
        children: []
      },
      {
        fullName: "Hakeem R. Reeves",
        badgeNumber: 57545,
        personifyNumber: 1619071338399,
        location: "Introd",
        expoBadge: false,
        bruteForceLock: false,
        password: "KIO11VDM3CZ",
        userName: "elementum.sem.vitae@Phasellusfermentum.org",
        emailAddress: "Vivamus@egestasa.net",
        memberType: "AI",
        children: []
      },
      {
        fullName: "Hoyt X. Schwartz",
        badgeNumber: 83199,
        personifyNumber: 1688073003799,
        location: "Napier",
        expoBadge: false,
        bruteForceLock: false,
        password: "PWH53GZD0HX",
        userName: "sed@Nuncmauriselit.com",
        emailAddress: "amet.consectetuer.adipiscing@ullamcorpervelit.edu",
        memberType: "",
        children: []
      },
      {
        fullName: "Yuli L. Head",
        badgeNumber: 43765,
        personifyNumber: 1660072474999,
        location: "Fraser Lake",
        expoBadge: true,
        bruteForceLock: false,
        password: "FHL57QDR5ZH",
        userName: "vitae.risus.Duis@estconguea.org",
        emailAddress: "et@sedconsequat.com",
        memberType: "AI",
        children: []
      },
      {
        fullName: "Ashely C. Mosley",
        badgeNumber: 70642,
        personifyNumber: 1656060274899,
        location: "Omal",
        expoBadge: false,
        bruteForceLock: false,
        password: "EKA37GJE6VE",
        userName: "nec@laciniamattis.org",
        emailAddress: "sociis@sollicitudin.co.uk",
        memberType: "",
        children: []
      },
      {
        fullName: "Byron C. Watts",
        badgeNumber: 41990,
        personifyNumber: 1695101603899,
        location: "100 Mile House",
        expoBadge: false,
        bruteForceLock: false,
        password: "OWG66PCB3HP",
        userName: "Aliquam@arcuimperdiet.org",
        emailAddress: "tellus.justo.sit@purusDuis.net",
        memberType: "",
        children: []
      },
      {
        fullName: "Kai A. Wilder",
        badgeNumber: 48701,
        personifyNumber: 1610120634999,
        location: "Warri",
        expoBadge: false,
        bruteForceLock: false,
        password: "FQQ09WHQ5JI",
        userName: "Proin.sed.turpis@vitae.ca",
        emailAddress: "metus@diamProindolor.net",
        memberType: "NPI",
        children: []
      },
      {
        fullName: "Imani F. Duke",
        badgeNumber: 43885,
        personifyNumber: 1643012149699,
        location: "Orosei",
        expoBadge: false,
        bruteForceLock: false,
        password: "NRS49HIN5CZ",
        userName: "dictum.eu@vestibulumMaurismagna.ca",
        emailAddress: "sed.leo.Cras@purus.org",
        memberType: "",
        children: []
      },
      {
        fullName: "Iris Y. Rodriquez",
        badgeNumber: 46031,
        personifyNumber: 1647020234199,
        location: "Velletri",
        expoBadge: true,
        bruteForceLock: false,
        password: "ZKU73HBY9QS",
        userName: "lorem.ut.aliquam@velarcu.net",
        emailAddress: "et.netus.et@laoreetliberoet.edu",
        memberType: "",
        children: []
      },
      {
        fullName: "Rhiannon B. Grant",
        badgeNumber: 66854,
        personifyNumber: 1636102024199,
        location: "Connah's Quay",
        expoBadge: false,
        bruteForceLock: false,
        password: "WFZ48VPD2MU",
        userName: "nulla@Nullamvitaediam.edu",
        emailAddress: "luctus.lobortis.Class@nonlaciniaat.net",
        memberType: "AA",
        children: []
      },
      {
        fullName: "Elton B. Mason",
        badgeNumber: 2152,
        personifyNumber: 1629101227199,
        location: "Sant'Elena",
        expoBadge: true,
        bruteForceLock: false,
        password: "IUC97LSF3AR",
        userName: "Curabitur@cursusIntegermollis.org",
        emailAddress: "mi@Phasellusdolor.ca",
        memberType: "AI",
        children: []
      },
      {
        fullName: "Samson D. Cardenas",
        badgeNumber: 86561,
        personifyNumber: 1629090243799,
        location: "Russell",
        expoBadge: true,
        bruteForceLock: false,
        password: "DTB99ZON9RS",
        userName: "Suspendisse.aliquet@amet.net",
        emailAddress: "Nam.ligula.elit@famesacturpis.org",
        memberType: "AA",
        children: []
      },
      {
        fullName: "Porter L. Cobb",
        badgeNumber: 93070,
        personifyNumber: 1631051640399,
        location: "Sunshine Coast Regional District",
        expoBadge: true,
        bruteForceLock: false,
        password: "BBU91LAB6CZ",
        userName: "metus.Aliquam@velit.ca",
        emailAddress: "orci.lacus@dolor.com",
        memberType: "FACC",
        children: []
      },
      {
        fullName: "Rigel H. Henry",
        badgeNumber: 80501,
        personifyNumber: 1650092288999,
        location: "Saint-Dizier",
        expoBadge: false,
        bruteForceLock: false,
        password: "OYT62TMJ8RU",
        userName: "in@non.edu",
        emailAddress: "fermentum@vehicularisusNulla.edu",
        memberType: "AI",
        children: []
      }
    ],
    singleReturn: [],
    passwordPart1: [
      "draw",
      "fate",
      "sail",
      "use",
      "eaux",
      "risk",
      "deck",
      "mail",
      "shop",
      "road",
      "fax",
      "pan",
      "jest",
      "bald",
      "copy",
      "act",
      "fill",
      "put",
      "dip",
      "hero",
      "sick",
      "pack",
      "tire",
      "rush",
      "drum"
    ],
    passwordPart2: [
      "54",
      "50",
      "48",
      "7",
      "36",
      "21",
      "99",
      "45",
      "23",
      "12",
      "62",
      "10",
      "6",
      "83",
      "7",
      "1",
      "14",
      "89",
      "85",
      "38",
      "36",
      "88",
      "89",
      "25",
      "23",
      "24"
    ],
    passwordPart3: [
      "need",
      "tie",
      "mask",
      "lazy",
      "fork",
      "see",
      "team",
      "bald",
      "fly",
      "give",
      "beam",
      "dine",
      "halt",
      "rice",
      "boom",
      "mild",
      "want",
      "path",
      "draw",
      "dare",
      "far",
      "just",
      "duty",
      "game",
      "pig",
      "lost"
    ]
  },
  mutations: {
    UNLINK_ACCOUNT: function(state, payload) {
      console.log(payload);
      let parent = payload.parent,
        child = payload.child;
      let parentIndex = state.searchReturn.indexOf(parent),
        childIndex = state.searchReturn[parentIndex].children.indexOf(child);
      state.searchReturn[parentIndex].children.splice(childIndex, 1);
      state.searchReturn.unshift(child);
    },
    ADD_SEARCH_HISTORY: function(state, result) {
      let date = new Date(),
        timestamp = date.toLocaleString();
      result["timestamp"] = timestamp;
      state.searchHistory.unshift(result);
      state.searchHistoryNew = true;
      state.searchHistory = state.searchHistory.slice(
        0,
        Math.max(15, state.searchHistory.length - 1)
      );
    },
    REPLACE_MEMBER_DATA: function(state, member) {
      let index = state.searchReturn.indexOf(member);
      if (index !== -1) {
        state.searchReturn[index] = member;
      }
    },
    SET_SINGLE_RESULT: function(state, result) {
      state.singleReturn = result;
      let date = new Date(),
        timestamp = date.toLocaleString();
      let packet = Object({
        sharedBy: state.adminUserName,
        timestamp: timestamp,
        memberName: result.fullName,
        memberType: result.memberType,
        badgeNumber: result.badgeNumber,
        personifyNumber: result.personifyNumber,
        emailAddress: result.emailAddress
      });
      state.sharesNew = true;
      state.shares.unshift(packet);
    },
    HISTORY_NEW_OFF: function(state) {
      state.searchHistoryNew = false;
    },
    SHARE_NEW_OFF: function(state) {
      state.sharesNew = false;
    }
  },
  getters: {
    searchHistoryCount: function(state) {
      return state.searchHistory.length;
    }
  },
  actions: {
    replaceMemberData({ commit }) {
      commit("REPLACE_MEMBER_DATA");
    }
  }
});
